export enum HydrusSortType {
  FileSize = 0,
  Duration = 1,
  ImportTime = 2,
  MIME = 3,
  Random = 4,
  Width = 5,
  Height = 6,
  Ratio = 7,
  NumPixels = 8,
  NumTags = 9,
  MediaViews = 10,
  MediaViewtime = 11,
  ApproxBitrate = 12,
  HasAudio = 13,
  FileModifiedTimestamp = 14,
  Framerate = 15,
  NumFrames = 16,
  //NumCollectionFiles = 17, Not used in API
  LastViewedTime = 18,
  ArchivedTimestamp = 19,
  Hash = 20,
}
