// Based on https://github.com/hydrusnetwork/hydrus/blob/master/hydrus/core/HydrusConstants.py

enum HydrusSpecificFiletype {
  APPLICATION_HYDRUS_CLIENT_COLLECTION = 0,
  IMAGE_JPEG = 1,
  IMAGE_PNG = 2,
  IMAGE_GIF = 3,
  IMAGE_BMP = 4,
  APPLICATION_FLASH = 5,
  APPLICATION_YAML = 6,
  IMAGE_ICON = 7,
  TEXT_HTML = 8,
  VIDEO_FLV = 9,
  APPLICATION_PDF = 10,
  APPLICATION_ZIP = 11,
  APPLICATION_HYDRUS_ENCRYPTED_ZIP = 12,
  AUDIO_MP3 = 13,
  VIDEO_MP4 = 14,
  AUDIO_OGG = 15,
  AUDIO_FLAC = 16,
  AUDIO_WMA = 17,
  VIDEO_WMV = 18,
  UNDETERMINED_WM = 19,
  VIDEO_MKV = 20,
  VIDEO_WEBM = 21,
  APPLICATION_JSON = 22,
  IMAGE_APNG = 23,
  UNDETERMINED_PNG = 24,
  VIDEO_MPEG = 25,
  VIDEO_MOV = 26,
  VIDEO_AVI = 27,
  APPLICATION_HYDRUS_UPDATE_DEFINITIONS = 28,
  APPLICATION_HYDRUS_UPDATE_CONTENT = 29,
  TEXT_PLAIN = 30,
  APPLICATION_RAR = 31,
  APPLICATION_7Z = 32,
  IMAGE_WEBP = 33,
  IMAGE_TIFF = 34,
  APPLICATION_PSD = 35,
  AUDIO_M4A = 36,
  VIDEO_REALMEDIA = 37,
  AUDIO_REALMEDIA = 38,
  AUDIO_TRUEAUDIO = 39,
  GENERAL_AUDIO = 40,
  GENERAL_IMAGE = 41,
  GENERAL_VIDEO = 42,
  GENERAL_APPLICATION = 43,
  GENERAL_ANIMATION = 44,
  APPLICATION_CLIP = 45,
  AUDIO_WAVE = 46,
  VIDEO_OGV = 47,
  AUDIO_MKV = 48,
  AUDIO_MP4 = 49,
  UNDETERMINED_MP4 = 50,
  APPLICATION_CBOR = 51,
  APPLICATION_WINDOWS_EXE = 52,
  AUDIO_WAVPACK = 53,
  APPLICATION_OCTET_STREAM = 100,
  APPLICATION_UNKNOWN = 101
}

const searchableFileTypes = [
  HydrusSpecificFiletype.IMAGE_JPEG,
  HydrusSpecificFiletype.IMAGE_PNG,
  HydrusSpecificFiletype.IMAGE_APNG,
  HydrusSpecificFiletype.IMAGE_GIF,
  HydrusSpecificFiletype.IMAGE_WEBP,
  HydrusSpecificFiletype.IMAGE_TIFF,
  HydrusSpecificFiletype.IMAGE_ICON,
  HydrusSpecificFiletype.APPLICATION_FLASH,
  HydrusSpecificFiletype.VIDEO_AVI,
  HydrusSpecificFiletype.VIDEO_FLV,
  HydrusSpecificFiletype.VIDEO_MOV,
  HydrusSpecificFiletype.VIDEO_MP4,
  HydrusSpecificFiletype.VIDEO_MKV,
  HydrusSpecificFiletype.VIDEO_REALMEDIA,
  HydrusSpecificFiletype.VIDEO_WEBM,
  HydrusSpecificFiletype.VIDEO_OGV,
  HydrusSpecificFiletype.VIDEO_MPEG,
  HydrusSpecificFiletype.APPLICATION_CLIP,
  HydrusSpecificFiletype.APPLICATION_PSD,
  HydrusSpecificFiletype.APPLICATION_PDF,
  HydrusSpecificFiletype.APPLICATION_ZIP,
  HydrusSpecificFiletype.APPLICATION_RAR,
  HydrusSpecificFiletype.APPLICATION_7Z,
  HydrusSpecificFiletype.AUDIO_M4A,
  HydrusSpecificFiletype.AUDIO_MP3,
  HydrusSpecificFiletype.AUDIO_REALMEDIA,
  HydrusSpecificFiletype.AUDIO_OGG,
  HydrusSpecificFiletype.AUDIO_FLAC,
  HydrusSpecificFiletype.AUDIO_WAVE,
  HydrusSpecificFiletype.AUDIO_TRUEAUDIO,
  HydrusSpecificFiletype.AUDIO_WMA,
  HydrusSpecificFiletype.VIDEO_WMV,
  HydrusSpecificFiletype.AUDIO_MKV,
  HydrusSpecificFiletype.AUDIO_MP4,
  HydrusSpecificFiletype.AUDIO_WAVPACK
]

const mime_string_lookup: Record<HydrusSpecificFiletype, string> = {
[HydrusSpecificFiletype.APPLICATION_HYDRUS_CLIENT_COLLECTION] : 'collection',
[HydrusSpecificFiletype.IMAGE_JPEG] : 'jpeg',
[HydrusSpecificFiletype.IMAGE_PNG] : 'png',
[HydrusSpecificFiletype.IMAGE_APNG] : 'apng',
[HydrusSpecificFiletype.IMAGE_GIF] : 'gif',
[HydrusSpecificFiletype.IMAGE_BMP] : 'bmp',
[HydrusSpecificFiletype.IMAGE_WEBP] : 'webp',
[HydrusSpecificFiletype.IMAGE_TIFF] : 'tiff',
[HydrusSpecificFiletype.IMAGE_ICON] : 'icon',
[HydrusSpecificFiletype.APPLICATION_FLASH] : 'flash',
[HydrusSpecificFiletype.APPLICATION_OCTET_STREAM] : 'application/octet-stream',
[HydrusSpecificFiletype.APPLICATION_YAML] : 'yaml',
[HydrusSpecificFiletype.APPLICATION_JSON] : 'json',
[HydrusSpecificFiletype.APPLICATION_CBOR] : 'cbor',
[HydrusSpecificFiletype.APPLICATION_PDF] : 'pdf',
[HydrusSpecificFiletype.APPLICATION_PSD] : 'photoshop psd',
[HydrusSpecificFiletype.APPLICATION_CLIP] : 'clip',
[HydrusSpecificFiletype.APPLICATION_ZIP] : 'zip',
[HydrusSpecificFiletype.APPLICATION_RAR] : 'rar',
[HydrusSpecificFiletype.APPLICATION_7Z] : '7z',
[HydrusSpecificFiletype.APPLICATION_WINDOWS_EXE] : 'windows exe',
[HydrusSpecificFiletype.APPLICATION_HYDRUS_ENCRYPTED_ZIP] : 'application/hydrus-encrypted-zip',
[HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_CONTENT] : 'application/hydrus-update-content',
[HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_DEFINITIONS] : 'application/hydrus-update-definitions',
[HydrusSpecificFiletype.AUDIO_M4A] : 'm4a',
[HydrusSpecificFiletype.AUDIO_MP3] : 'mp3',
[HydrusSpecificFiletype.AUDIO_OGG] : 'ogg',
[HydrusSpecificFiletype.AUDIO_FLAC] : 'flac',
[HydrusSpecificFiletype.AUDIO_MKV] : 'matroska audio',
[HydrusSpecificFiletype.AUDIO_MP4] : 'mp4 audio',
[HydrusSpecificFiletype.AUDIO_WAVE] : 'wave',
[HydrusSpecificFiletype.AUDIO_REALMEDIA] : 'realaudio',
[HydrusSpecificFiletype.AUDIO_TRUEAUDIO] : 'tta',
[HydrusSpecificFiletype.AUDIO_WMA] : 'wma',
[HydrusSpecificFiletype.AUDIO_WAVPACK] : 'wavpack',
[HydrusSpecificFiletype.TEXT_HTML] : 'html',
[HydrusSpecificFiletype.TEXT_PLAIN] : 'plaintext',
[HydrusSpecificFiletype.VIDEO_AVI] : 'avi',
[HydrusSpecificFiletype.VIDEO_FLV] : 'flv',
[HydrusSpecificFiletype.VIDEO_MOV] : 'quicktime',
[HydrusSpecificFiletype.VIDEO_MP4] : 'mp4',
[HydrusSpecificFiletype.VIDEO_MPEG] : 'mpeg',
[HydrusSpecificFiletype.VIDEO_WMV] : 'wmv',
[HydrusSpecificFiletype.VIDEO_MKV] : 'matroska',
[HydrusSpecificFiletype.VIDEO_OGV] : 'ogv',
[HydrusSpecificFiletype.VIDEO_REALMEDIA] : 'realvideo',
[HydrusSpecificFiletype.VIDEO_WEBM] : 'webm',
[HydrusSpecificFiletype.UNDETERMINED_WM] : 'wma or wmv',
[HydrusSpecificFiletype.UNDETERMINED_MP4] : 'mp4 with or without audio',
[HydrusSpecificFiletype.UNDETERMINED_PNG] : 'png or apng',
[HydrusSpecificFiletype.APPLICATION_UNKNOWN] : 'unknown filetype',
[HydrusSpecificFiletype.GENERAL_APPLICATION] : 'application',
[HydrusSpecificFiletype.GENERAL_AUDIO] : 'audio',
[HydrusSpecificFiletype.GENERAL_IMAGE] : 'image',
[HydrusSpecificFiletype.GENERAL_VIDEO] : 'video',
[HydrusSpecificFiletype.GENERAL_ANIMATION] : 'animation'
}

const mime_mimetype_string_lookup: Partial<Record<HydrusSpecificFiletype, string>> = {
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_CLIENT_COLLECTION] : 'collection',
  [HydrusSpecificFiletype.IMAGE_JPEG] : 'image/jpeg',
  [HydrusSpecificFiletype.IMAGE_PNG] : 'image/png',
  [HydrusSpecificFiletype.IMAGE_APNG] : 'image/apng',
  [HydrusSpecificFiletype.IMAGE_GIF] : 'image/gif',
  [HydrusSpecificFiletype.IMAGE_BMP] : 'image/bmp',
  [HydrusSpecificFiletype.IMAGE_WEBP] : 'image/webp',
  [HydrusSpecificFiletype.IMAGE_TIFF] : 'image/tiff',
  [HydrusSpecificFiletype.IMAGE_ICON] : 'image/x-icon',
  [HydrusSpecificFiletype.APPLICATION_FLASH] : 'application/x-shockwave-flash',
  [HydrusSpecificFiletype.APPLICATION_OCTET_STREAM] : 'application/octet-stream',
  [HydrusSpecificFiletype.APPLICATION_YAML] : 'application/x-yaml',
  [HydrusSpecificFiletype.APPLICATION_JSON] : 'application/json',
  [HydrusSpecificFiletype.APPLICATION_CBOR] : 'application/cbor',
  [HydrusSpecificFiletype.APPLICATION_PDF] : 'application/pdf',
  [HydrusSpecificFiletype.APPLICATION_PSD] : 'application/x-photoshop',
  [HydrusSpecificFiletype.APPLICATION_CLIP] : 'application/clip',
  [HydrusSpecificFiletype.APPLICATION_ZIP] : 'application/zip',
  [HydrusSpecificFiletype.APPLICATION_RAR] : 'application/vnd.rar',
  [HydrusSpecificFiletype.APPLICATION_7Z] : 'application/x-7z-compressed',
  [HydrusSpecificFiletype.APPLICATION_WINDOWS_EXE] : 'application/octet-stream',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_ENCRYPTED_ZIP] : 'application/hydrus-encrypted-zip',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_CONTENT] : 'application/hydrus-update-content',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_DEFINITIONS] : 'application/hydrus-update-definitions',
  [HydrusSpecificFiletype.AUDIO_M4A] : 'audio/mp4',
  [HydrusSpecificFiletype.AUDIO_MP3] : 'audio/mp3',
  [HydrusSpecificFiletype.AUDIO_OGG] : 'audio/ogg',
  [HydrusSpecificFiletype.AUDIO_FLAC] : 'audio/flac',
  [HydrusSpecificFiletype.AUDIO_MKV] : 'audio/x-matroska',
  [HydrusSpecificFiletype.AUDIO_MP4] : 'audio/mp4',
  [HydrusSpecificFiletype.AUDIO_WAVE] : 'audio/x-wav',
  [HydrusSpecificFiletype.AUDIO_REALMEDIA] : 'audio/vnd.rn-realaudio',
  [HydrusSpecificFiletype.AUDIO_TRUEAUDIO] : 'audio/x-tta',
  [HydrusSpecificFiletype.AUDIO_WMA] : 'audio/x-ms-wma',
  [HydrusSpecificFiletype.AUDIO_WAVPACK] : 'audio/wavpack',
  [HydrusSpecificFiletype.TEXT_HTML] : 'text/html',
  [HydrusSpecificFiletype.TEXT_PLAIN] : 'text/plain',
  [HydrusSpecificFiletype.VIDEO_AVI] : 'video/x-msvideo',
  [HydrusSpecificFiletype.VIDEO_FLV] : 'video/x-flv',
  [HydrusSpecificFiletype.VIDEO_MOV] : 'video/quicktime',
  [HydrusSpecificFiletype.VIDEO_MP4] : 'video/mp4',
  [HydrusSpecificFiletype.VIDEO_MPEG] : 'video/mpeg',
  [HydrusSpecificFiletype.VIDEO_WMV] : 'video/x-ms-wmv',
  [HydrusSpecificFiletype.VIDEO_MKV] : 'video/x-matroska',
  [HydrusSpecificFiletype.VIDEO_OGV] : 'video/ogg',
  [HydrusSpecificFiletype.VIDEO_REALMEDIA] : 'video/vnd.rn-realvideo',
  [HydrusSpecificFiletype.VIDEO_WEBM] : 'video/webm',
  [HydrusSpecificFiletype.APPLICATION_UNKNOWN] : 'unknown filetype',
  [HydrusSpecificFiletype.GENERAL_APPLICATION] : 'application',
  [HydrusSpecificFiletype.GENERAL_AUDIO] : 'audio',
  [HydrusSpecificFiletype.GENERAL_IMAGE] : 'image',
  [HydrusSpecificFiletype.GENERAL_VIDEO] : 'video',
  [HydrusSpecificFiletype.GENERAL_ANIMATION] : 'animation'
}

const mime_ext_lookup: Partial<Record<HydrusSpecificFiletype, string>> = {
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_CLIENT_COLLECTION] : '.collection',
  [HydrusSpecificFiletype.IMAGE_JPEG] : '.jpg',
  [HydrusSpecificFiletype.IMAGE_PNG] : '.png',
  [HydrusSpecificFiletype.IMAGE_APNG] : '.png',
  [HydrusSpecificFiletype.IMAGE_GIF] : '.gif',
  [HydrusSpecificFiletype.IMAGE_BMP] : '.bmp',
  [HydrusSpecificFiletype.IMAGE_WEBP] : '.webp',
  [HydrusSpecificFiletype.IMAGE_TIFF] : '.tiff',
  [HydrusSpecificFiletype.IMAGE_ICON] : '.ico',
  [HydrusSpecificFiletype.APPLICATION_FLASH] : '.swf',
  [HydrusSpecificFiletype.APPLICATION_OCTET_STREAM] : '.bin',
  [HydrusSpecificFiletype.APPLICATION_YAML] : '.yaml',
  [HydrusSpecificFiletype.APPLICATION_JSON] : '.json',
  [HydrusSpecificFiletype.APPLICATION_PDF] : '.pdf',
  [HydrusSpecificFiletype.APPLICATION_PSD] : '.psd',
  [HydrusSpecificFiletype.APPLICATION_CLIP] : '.clip',
  [HydrusSpecificFiletype.APPLICATION_ZIP] : '.zip',
  [HydrusSpecificFiletype.APPLICATION_RAR] : '.rar',
  [HydrusSpecificFiletype.APPLICATION_7Z] : '.7z',
  [HydrusSpecificFiletype.APPLICATION_WINDOWS_EXE] : '.exe',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_ENCRYPTED_ZIP] : '.zip.encrypted',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_CONTENT] : '',
  [HydrusSpecificFiletype.APPLICATION_HYDRUS_UPDATE_DEFINITIONS] : '',
  [HydrusSpecificFiletype.AUDIO_M4A] : '.m4a',
  [HydrusSpecificFiletype.AUDIO_MP3] : '.mp3',
  [HydrusSpecificFiletype.AUDIO_MKV] : '.mkv',
  [HydrusSpecificFiletype.AUDIO_MP4] : '.mp4',
  [HydrusSpecificFiletype.AUDIO_OGG] : '.ogg',
  [HydrusSpecificFiletype.AUDIO_REALMEDIA] : '.ra',
  [HydrusSpecificFiletype.AUDIO_FLAC] : '.flac',
  [HydrusSpecificFiletype.AUDIO_WAVE] : '.wav',
  [HydrusSpecificFiletype.AUDIO_TRUEAUDIO] : '.tta',
  [HydrusSpecificFiletype.AUDIO_WMA] : '.wma',
  [HydrusSpecificFiletype.AUDIO_WAVPACK] : '.wv',
  [HydrusSpecificFiletype.TEXT_HTML] : '.html',
  [HydrusSpecificFiletype.TEXT_PLAIN] : '.txt',
  [HydrusSpecificFiletype.VIDEO_AVI] : '.avi',
  [HydrusSpecificFiletype.VIDEO_FLV] : '.flv',
  [HydrusSpecificFiletype.VIDEO_MOV] : '.mov',
  [HydrusSpecificFiletype.VIDEO_MP4] : '.mp4',
  [HydrusSpecificFiletype.VIDEO_MPEG] : '.mpeg',
  [HydrusSpecificFiletype.VIDEO_WMV] : '.wmv',
  [HydrusSpecificFiletype.VIDEO_MKV] : '.mkv',
  [HydrusSpecificFiletype.VIDEO_OGV] : '.ogv',
  [HydrusSpecificFiletype.VIDEO_REALMEDIA] : '.rm',
  [HydrusSpecificFiletype.VIDEO_WEBM] : '.webm',
  [HydrusSpecificFiletype.APPLICATION_UNKNOWN] : ''
}

export const searchFiletypes = searchableFileTypes.map(ft => ({
  mime: mime_mimetype_string_lookup[ft],
  name: mime_string_lookup[ft]
}))
